### ISSUE TITLE
Missing `table-responsive`.

### ISSUE THREAD

**Issue by rogeriotaques** [AbtzLabs/seed-css#55]
Too long tables break on small devices. Adding a wrapper such as below fixes the issue:

```html
<div class="table-responsive" >
   // table here
</div>
```

with style: 
```css
.table-responsive {
   position: relative;
   width: 100%;
   overflow-x: auto;
}
```
