### ISSUE TITLE
Tooltip min/max-width

### ISSUE THREAD

**Issue by rogeriotaques** [AbtzLabs/seed-css#61]
Tooltip has not a min-width which looks weird on some occasions. It can be fixed by defining the following rules to the `tooltip.scss`:

```css
.with-tooltip {
   /* ... */
   width: max-content;
   max-width: 250px;
   min-width: 100px;
   /* ... */
}
```
